name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Setup NodeJS 14 💎
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies & Build Project 🔧
        run: |
          npm install
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          single-commit: true
          branch: gh-pages
          folder: public
          clean: true
